### ISSUE TITLE
Fix Flaky test

### ISSUE THREAD

**Issue by drumnkyle** [drumnkyle/music-notation-core#138]
`TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration` is flaky somehow. The problem is that the `notes` array is somehow empty. The following is the backtrace:

```
#6	0x0000000103418eee in Tuplet.removeNotesRecursive(at:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:416
#7	0x00000001034173e8 in Tuplet.removeNotes(at:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:439
#8	0x0000000103413018 in Tuplet.replaceNotes(at:with:firstNoteIndex:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:361
#9	0x0000000103411f56 in Tuplet.replaceNotes<A>(in:with:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:168
#10	0x00000001088a00b9 in closure #1 in TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration() at /Users/kyle/dev/OpenSource/music-notation-core/Tests/MusicNotationCoreTests/TupletTests.swift:1146
#11	0x00000001088a0760 in partial apply for closure #1 in TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration() ()
#12	0x00000001089e78fd in XCTestCase.assertNoErrorThrown(inFile:atLine:expression:) at /Users/kyle/dev/OpenSource/music-notation-core/Tests/MusicNotationCoreTests/TestHelpers.swift:33
#13	0x000000010889f167 in TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration() at /Users/kyle/dev/OpenSource/music-notation-core/Tests/MusicNotationCoreTests/TupletTests.swift:1143
```

**Comment by sprzenus** [comment]
The problem with the flakiness of this test is in converting Array to Set, which loses the order of its items. I propose removing duplicates not losing the order of the array, but it still shows weak points of `Tuplet.removeNotes(at:)` private method. When I changed converting Array to Set, tests (this and `testReplaceNotesFromFirstToSecondToLastInTupletWithNotesOfSameDuration`) have started to crash on every run, because `notes` property is mutated, but flatIndexes given for removal aren't. 

In this case, we have some choice, what to do with it:
- Keep the old value of `notes` and remove in the other one copy of it (preferred by me).
- Update flatIndexes after removal

**Comment by drumnkyle** [comment]
I’m not sure I understand your preferred fix. Can you give a little more detail on that?

**Comment by sprzenus** [comment]
Of course! We should temporarily copy notes and work on two copies. One to get notes of it, second to mutate. It requires `NoteCollection` to be Equatable, which is almost done, as I see. If you have a better idea for a more optimized solution, let know.

**Comment by drumnkyle** [comment]
Hmm. Ok. Let me look at the details and get back to you.

**Comment by drumnkyle** [comment]
I was just walked through the code after changing everything to arrays instead of Sets. It seems to me that the problem is that for some reason it is doing a map in the outer `removeNotes` method in the `.map.filter` section so that it ends up having 6 versions of the same array of notes to remove. Then, within the recursive method it does the same thing again. So, it ends up removing all the notes in the first pass, but then it tries to keep doing it multiple times but the notes are already removed.

So, the problem is trying to figure out why we had those map and filter methods. It may have been that in an older Swift version that functioned differently maybe... That would be my guess. 

From what I can remember and looking at the code, I think the purpose of that was to make it so that we group all of the indexes in the same tuplet together so we remove all the notes in 1 tuplet, then move onto the next tuplet (for the compound tuplet case). But I think the map and filter together are making way too many versions of it.

Let me know if you understand what I'm saying and want to take another look at it. If not, I can probably try to take care of this one as it's kind of weird. Or let me know if you have more questions.

**Comment by sprzenus** [comment]
After changing it to have to arrays - one for getting the object and second one to mutate, I see that losing order isn't the thing. It caused flakiness in tests, but it wasn't an issue. The issue was that this case in the test failed. As I said before, it is one of two ways of solving the problem.

I took a look at `.map.filter` calls and I see that it's there for grouping elements. Could you describe in an example what you mean?
